

version: 2

run:
  timeout: 5m
  go: "1.24"
  tests: false

linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'error return value not checked.*(Close|Write|Stop|Flush)'
  exclude-rules:
    - path: internal/repository/gormrepo
      linters:
        - dupl
    - path: internal/admin/helpers.go
      linters:
        - misspell
    - path: internal/db/migrate.go
      linters:
        - misspell
