server:
  port: "8080"
  enable_swagger: false

database:
  type: "postgres"
  dsn: "postgres://user:password@db:5432/gamelink?sslmode=disable"

cache:
  type: "redis"
  redis:
    addr: "redis:6379"
    password: ""
    db: 0
