// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"gamelink/pkg/lifecycle"
	"gamelink/pkg/metrics"
	"github.com/prometheus/client_golang/prometheus"
)

// Injectors from wire.go:

func initializeApplication() (*Application, error) {
	appConfig, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(appConfig)
	if err != nil {
		return nil, err
	}
	registry := lifecycle.NewRegistry()
	sqlDB, err := ProvideSQLDB(registry, db)
	if err != nil {
		return nil, err
	}
	cache, err := ProvideCache(appConfig, registry)
	if err != nil {
		return nil, err
	}
	adminService := ProvideAdminService(db, cache)
	router := ProvideRouter(appConfig, db, sqlDB, cache, adminService, registry)
	engine := ProvideEngine(router)
	manager := lifecycle.NewManager(registry)
	prometheusRegistry := prometheus.NewRegistry()
	metrics.Init(prometheusRegistry)
	metrics.InitBusinessMetrics(prometheusRegistry)
	application := &Application{
		Engine:             engine,
		Config:             appConfig,
		Lifecycle:          manager,
		PrometheusRegistry: prometheusRegistry,
	}
	return application, nil
}
