# 开发环境配置文件
# 用于本地开发和测试

server:
  port: "8080"
  enable_swagger: true

database:
  type: "sqlite"
  dsn: "file:./var/dev.db?mode=rwc&_pragma=busy_timeout(5000)&_pragma=foreign_keys(1)"

cache:
  type: "memory"
  redis:
    addr: "127.0.0.1:6379"
    password: ""
    db: 0
