# 生产环境配置文件
# 用于生产环境部署

server:
  port: "8080"
  enable_swagger: false

database:
  type: "postgres"
  # dsn intentionally left blank for production; set via env DB_DSN
  dsn: ""

cache:
  type: "redis"
  redis:
    addr: "127.0.0.1:6379"
    password: ""
    db: 0
