name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Go Modules Download
        run: go mod download

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56
          working-directory: backend
          args: --timeout 5m

      - name: Vet
        run: go vet ./...

      - name: Test (race + coverage)
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.out

      - name: Build
        run: go build -v ./...